---

- name: ensure docker.io package is installed
  apt: name=docker.io

- name: ensure docker group exists
  group: name="{{item}}" state=present
  with_items:
    - docker
    - admin

- name: ensure docker group exists
  group: name=docker state=present

- name: ensure admin user exists and is member of docker group
  user: name=admin group=admin append=yes groups=docker state=present
  notify: 
    - restart docker
