---

- name: ensure docker.io package is installed
  apt: name=docker.io

- name: ensure docker group exists
  group: name="{{item}}" state=present
  with_items:
    - docker
    - admin

- name: ensure admin and harbormaster users exists and is member of docker group
  user: name="{{item}}" group=admin append=yes groups=docker state=present
  with_items:
    - admin
    - git
  notify: 
    - restart docker
